# config/services.yaml

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    plane_uploads_directory: '%kernel.project_dir%/var/uploads/planes'
    file_uploads_directory: '%kernel.project_dir%/var/uploads/files'
    file_previews_directory: '%kernel.project_dir%/var/uploads/files/previews'
    previews_url: '/uploads/files/previews'
    pdf_icon_path: '%kernel.project_dir%/public/images/Lucca.jpg'
    file_icon_path: '%kernel.project_dir%/public/images/Vinny.jpg'

services:
    App\Service\UserManagement:
        autowire: true
        autoconfigure: true
        public: false

    App\Security\Auth0UserProvider:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    hwi_oauth.user.provider.entity:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\EntityUserProvider
        arguments:
            - '@doctrine'  # Replace with your entity manager service if necessary
            - App\Entity\User  # Replace with your Symfony User entity class
            -  # Property mappings for OAuth providers
                'auth0': 'auth0'

    # default configuration for services in *this* file
    _defaults:
        bind:
            $uploadDirectory: '%kernel.project_dir%/public/uploads/images'
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\PlaneController:
        arguments:
            $planeUploadsDirectory: '%plane_uploads_directory%'

    App\Controller\MaintenanceLogController:
        arguments:
            $uploadsDirectory: '%file_uploads_directory%'
            $previewsDirectory: '%file_previews_directory%'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
